### ISSUE TITLE
Text String + Access Key Issue

### ISSUE THREAD

**Issue by jeetzz** [eheikes/aws-tts#11]
Hi,

Instead of giving a text file, can we not pass the text within the command and get it converted to speech?

example: aws-tts "hello, this is a test text to speech file using amazon polly" hello.mp3

Also, I am trying to add my AWS key but it keeps returning with help prompt.

using this command aws-tts --access-key --myaccesskeyhere

**Comment by eheikes** [comment]
> using this command aws-tts --access-key --myaccesskeyhere

You don't need to prefix the key itself with hyphens. The command should look like:

```
aws-tts --access-key myaccesskeyhere
```

Also note that usually you'll need to specify both the access key *and* the secret key (see [the AWS docs](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/getting-your-credentials.html)):

```
aws-tts --access-key myaccesskeyhere --secret-key secretkeyhere
```

**Comment by eheikes** [comment]
As of v1.2.0 you can now pipe in text from `stdin`. For example:

```
$ echo "hello, this is a test text to speech file using amazon polly" | aws-tts test.mp3
```
