### ISSUE TITLE
Support for lexicons

### ISSUE THREAD

**Issue by tgb** [eheikes/aws-tts#15]
AWS Polly allows lexicons (customized pronunciation files) to be used, but aws-tts doesn't support using these as far as I can tell. Any chance support for this could be added, even if users need to upload the lexicons separately through the console?

**Comment by eheikes** [comment]
Absolutely. At the very least it could accept an argument to be passed to Polly's `LexiconNames` parameter.

**Comment by eheikes** [comment]
A `lexicon` option is available in the v1.3.0 release now.
