### ISSUE TITLE
Stuck on Convert to Audio 0/1

### ISSUE THREAD

**Issue by Se7enPhoenix** [eheikes/aws-tts#18]
As the tile suggest, on the latest, I am getting this error, it just hangs on this. 

Is it working for others?

**Comment by eheikes** [comment]
It's working for me. :)

If aws-tts hangs during the "Convert to Audio" step, it's probably a network issue. Please make sure you can connect to AWS outside of aws-tts -- try going to https://polly.us-east-1.amazonaws.com/v1/speech (or whatever AWS region you're using) or using the [AWS CLI](https://github.com/aws/aws-cli) to run a command.

If there is an error, then aws-tts should eventually quit with an error (it may take 30 seconds or more with a networking error). Please provide additional info: the exact command you are running, and the output with any eventual error message you get.

**Comment by Se7enPhoenix** [comment]
That would make sense, when I trued npm to reinstall, I got a host not reachable. 

I have no idea what caused it. But, I rebooted today and seems to work right now. 

Thanks for the advice! 

I'm not a coder, so this has been super fun to play with!
