### ISSUE TITLE
Batch process- enhancement

### ISSUE THREAD

**Issue by sonodave** [eheikes/aws-tts#19]
A batch process that could load a list of documents to be run under a defined set of parameters for the entire run of documents. Sometimes I need to process 200 to 300 documents and it would be nice to be able to do a batch run since they are all set for the same parameters. A --batch tag that could pickup a text file with the documents names and default to naming the audio with the same title as the document. I am not much of a programmer so I don,t know if this is possible.

**Comment by tgb** [comment]
One way to do this if you're using macOS or Linux is to run the following terminal commands:

`for f in *.txt; do
  fn=${f%.txt};
  aws-tts $f ${fn##*/}.mp3 _--voice Mizuki --region eu-west-1_;
done`

It'll take all your .txt files in the current directory and turn them into mp3 files.

Alternatively, if you've got a file that contains a list of just the files to process, you could do this (assume it's called reprocess.txt):

``for f in `cat reprocess.txt`; do fn=${f%.txt}; aws-tts $f ${fn##*/}.mp3 _--voice Mizuki --region eu-west-1_; done``

I believe Windows can run BASH scripts now too, so you might be able to get it working there too if that's what you need.

**Comment by eheikes** [comment]
Yeah, I think this is outside the scope of aws-tts. As @tgb said, processing a series of documents should be pretty easy using the OSX/Linux/Unix shell or Windows Bash shell. Windows' PowerShell or batch files can also probably do it.
