### ISSUE TITLE
Fail gracefully if lexicon can't be found

### ISSUE THREAD

**Issue by tgb** [eheikes/aws-tts#20]
I was running aws-tts using a lexicon. Unfortunately, I uploaded the lexicon into the wrong region, so Polly wasn't able to locate the lexicon. The error that came out was:

> ✔ Reading text
> ✔ Splitting text
> ✖ Convert to audio (0/1)
> HTTPError
>     at EventEmitter.ee.on.res (/usr/local/lib/node_modules/aws-tts/node_modules/got/index.js:182:24)
>     at emitOne (events.js:115:13)
>     at EventEmitter.emit (events.js:210:7)
>     at Immediate.setImmediate (/usr/local/lib/node_modules/aws-tts/node_modules/got/index.js:61:8)
>     at runCallback (timers.js:800:20)
>     at tryOnImmediate (timers.js:762:5)
>     at processImmediate [as _immediateCallback] (timers.js:733:5)

Using Google on these results, I found Erik's website at https://ericheikes.com/text-speech-tool-aws-polly/#comment-63512 but reading that someone might think their credentials are wrong when they're actually correct (as they were in my case). It'd be really good if aws-tts could give more helpful output when there's an error, if that's possible - I haven't checked whether AWS sends anything more useful back in its errors.

**Comment by eheikes** [comment]
Error messages are now shown in v1.3.2
