### ISSUE TITLE
SSML submissions

### ISSUE THREAD

**Issue by wonderfullyrich** [eheikes/aws-tts#23]
Never mind... I didn't look at the options 

-------

Polly is capable of SSML submissions, but I'm not sure if aws-tts has a method to process an existing SSML document.  I did a trial on an SSML document, and it read it as text rather then SSML. 

It's this something I'll have to look elsewhere for or is it possible we'll see it here?

**Comment by sonodave** [comment]
I run SSML docs with aws-tts all the time.  Has to be encoded UTF-8 and have the --ssml tag in the command line.

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 19, 2018 at 11:38 PM, wonderfullyrich<notifications@github.com> wrote:   
Polly is capable of SSML submissions, but I'm not sure if aws-tts has a method to process an existing SSML document. I did a trial on an SSML document, and it read it as text rather then SSML.

It's this something I'll have to look elsewhere for or is it possible we'll see it here?
