### ISSUE TITLE
Beginner

### ISSUE THREAD

**Issue by lucisx10** [eheikes/aws-tts#24]
Hello there
can you do a quick video on how to setup stuff
i have windows , i downloaded the required files and encoder and got the aws credentials but didn't know how to get started using your aws-tts

**Comment by eheikes** [comment]
aws-tts is a Node.js command-line tool, so if you're not familiar with Node.js or the command line, there is a bit of a learning curve. However, it should be pretty easy to get up and running:

1. Download and install [Node.js](https://nodejs.org/).
1. Download and install [ffmpeg](https://ffmpeg.org/).
1. [Configure your machine with your AWS credentials](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html).
1. Go to the Windows menu and choose (or search for) "Node.js command prompt" under the Node.js section.
1. Run `npm install aws-tts -g` at the command prompt and wait for it to finish.
1. Now you can run aws-tts in the command prompt window. For example: `aws-tts C:\Users\Eric\Documents\test.txt C:\Users\Eric\Documents\test.mp3`. [Here's an article on how to use the Windows command prompt](https://www.digitalcitizen.life/command-prompt-how-use-basic-commands); there are many others out there.

Does that make sense? I've tried to outline this in the README. Let me know if you're running into any problems or if any part is unclear. Also check the new [Troubleshooting section](https://github.com/eheikes/aws-tts#troubleshooting) in the README.

Thanks!

**Comment by lucisx10** [comment]
![untitled](https://user-images.githubusercontent.com/23036761/35359839-f55ffd7a-015b-11e8-834f-0068bc1d60df.png)

How can i install ffmpeg ?
And how could i Configure my machine with my AWS credentials? do i create a file and put them on it ? the instructions of the link you gave me got me confused :p 

thnaks

**Comment by eheikes** [comment]
ffmpeg doesn't make it very easy, does it? I think I used [these instructions](http://adaptivesamples.com/how-to-install-ffmpeg-on-windows/) to install ffmpeg on Windows -- follow those instructions and give it another try.
